<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6PcfADK\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6PcfADK/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container6PcfADK.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container6PcfADK\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container6PcfADK\appAppKernelProdContainer([
    'container.build_hash' => '6PcfADK',
    'container.build_id' => '3bf45239',
    'container.build_time' => 1741049536,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6PcfADK');
