<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkJEnfh\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkJEnfh/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNkJEnfh.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNkJEnfh\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNkJEnfh\appAppKernelProdContainer([
    'container.build_hash' => 'NkJEnfh',
    'container.build_id' => '0d71343e',
    'container.build_time' => 1741044607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkJEnfh');
